version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/open62541"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/milo"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"

  - package-ecosystem: "maven"
    directory: "/milo"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    groups:
      milo-deps:
        patterns:
          - "org.eclipse.milo*"
